
# path to stuff
FFDIR       := ../..

PROGPORT    := /dev/ttyUSB0

# Arduino Nano clone
PROGPORT    := /dev/ttyUSB0
PROGSPEED   := 57600

DEBUGSPEED  := 115200

PRINTF      := float


# see build.mk for more options that can be set here

# include master makefile
include $(FFDIR)/build.mk
