
# path to stuff
FFDIR       := ../..


# see build.mk for more options that can be set here

# FTDI cable
DEBUGPORT   := /dev/ttyUSB0

# USBTinyISP programmer
AVRDUDEARGS := -c usbtiny -y -V -B 1

# include master makefile
include $(FFDIR)/build.mk
