
# path to stuff
FFDIR       := ../..

# Nano
PROGSPEED   := 57600
DEBUGPORT   := /dev/ttyUSB0


# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
