
# path to stuff
FFDIR       := ../..

# FTDI cable and standalone ("breadboard") Arduino
#PROGSPEED   := 57600
PROGPORT    := /dev/ttyUSB0

# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
