
# path to stuff
FFDIR       := ../..


PROJFILES   := $(wildcard *.c) ../ffmatrix-common/ffmatrix.c

# Arduino Nano clone
#PROGPORT    := /dev/ttyUSB0
#PROGSPEED   := 57600


# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
