
# path to stuff
FFDIR       := ../..

#PROGSPEED   := 57600
#PROGPORT    := /dev/ttyUSB0

PRINTF      := float

# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
