
# path to stuff
FFDIR       := ../..

# Nano
PROGSPEED   := 57600
DEBUGPORT   := /dev/ttyUSB0

# USBTinyISP programmer
#AVRDUDEARGS := -c usbtiny -V -B 1

# we want to printf() floats
#PRINTF      := float


# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
