
# path to stuff
FFDIR       := ../..


PROJFILES   := $(wildcard *.c) ../ffmatrix-common/ffmatrix.c

# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
