
# path to stuff
FFDIR       := ../..

PROGPORT    := /dev/ttyUSB0
AVRDUDEPROG := arduino
PROGSPEED   := 57600
DEBUGSPEED  := 9600

# see build.mk for more options that can be set here


# include master makefile
include $(FFDIR)/build.mk
